Repository typefaceoff/typefaceoff, pull requests merged in 2023-10, with the labels that each got.

#122 Feature/dark mode
  package.json
  pnpm-lock.yaml
  src/components/App.tsx
  src/index.css
  src/styles/App.css
  src/styles/ProofCenteredLine.css
  src/styles/ProofFullWidthLine.css
  src/styles/ProofHalfWidthLine.css
Labels: enhancement

#121 Feat/heading template
  src/components/App.tsx
  src/components/LineFormats/ProofTitleLine.tsx
  src/components/Template.tsx
  src/components/TemplatePlaceHolders/HeadingTextPlaceHolders.tsx
  src/styles/ProofTitleLine.css
Labels: enhancement

#126 Fix/heading highlight
  src/styles/App.css
  src/styles/ProofTitleLine.css
Labels: bug

#128 refactor - remove duplicate code
  src/index.css
  src/styles/ProofCenteredLine.css
  src/styles/ProofFullWidthLine.css
  src/styles/ProofHalfWidthLine.css
Labels: enhancement

#134 Update README.md
  README.md
Labels: documentation

#135 Documentation/update roadmap
  .github/ROADMAP.md
Labels: documentation

#131 fix article header text
  src/components/TemplatePlaceHolders/ArticleTextPlaceHolders.tsx
  src/components/constants/index.tsx
Labels: bug

#139 bug(footer): Website Footer white in dark mode
  src/index.css
  src/styles/App.css
Labels: bug
